const CONFIG = {
  nombreNegocio:    "Odontología Especializada",
  nombreCorto:      "Odontología Especializada",
  slogan:           "Especialistas independientes, atención de excelencia",
  sloganHero:       "Especialistas en Odontología a Tu Servicio en Bogotá",
  subtituloHero:    "Un equipo de especialistas independientes certificados en ortodoncia, periodoncia, endodoncia y estética dental. Atención personalizada en Bogotá.",
  descripcionSobre: "Somos un grupo de especialistas odontológicos independientes reunidos en un mismo espacio para ofrecerte atención de excelencia en Bogotá. Cada profesional está habilitado de forma independiente ante la Secretaría de Salud, garantizando la más alta calidad y responsabilidad en cada tratamiento.",
  tipoPerfil:       "especialistas",
  ciudad:           "Bogotá",
  pais:             "Colombia",
  direccion:        "Calle 53b #24, Bogotá",
  consultorio:      "",
  regionSEO:        "CO-DC",
  whatsapp:         "573059370931",
  whatsappMensaje:  "Hola! Quiero agendar una cita con un especialista",
  telefono:         "+57 305 937 0931",
  email:            "",
  instagram:        "",
  instagramURL:     "",
  facebook:         "",
  facebookURL:      "",
  tiktok:           "",
  tiktokURL:        "",
  horarioSemana:    "Lunes a Viernes: 8:00am - 6:00pm",
  horarioSabado:    "Sábados: 8:00am - 2:00pm",
  horarioDomingo:   "",
  colores: {
    primario:        "#C9A87C",
    primarioDeep:    "#A8864A",
    primarioMedio:   "#D4B88A",
    primarioLight:   "#E8D5B8",
    primarioPale:    "#FAF5ED",
    primarioSubtle:  "#FDFAF6",
    oscuro:          "#1A1200",
    heroFondo:       "#1A1200",
    textoPrimario:   "#1A1200",
    textoSecundario: "#4A3A1A",
    textoMuted:      "#8A7A5A",
    fondo:           "#FFFFFF",
    fondoAlt:        "#FAF5ED",
  },
  tipografia: {
    titulos:    "Cormorant Garamond",
    subtitulos: "DM Sans",
    cuerpo:     "Inter",
  },
  stats: [
    { numero: "4",    label: "Especialistas",  sublabel: "Independientes certificados" },
    { numero: "4",    label: "Especialidades", sublabel: "Cobertura integral" },
    { numero: "100%", label: "Habilitados",    sublabel: "Secretaría de Salud" },
    { numero: "5★",   label: "Calificación",   sublabel: "Pacientes satisfechos" },
  ],
  especialistas: [
    {
      id:          "william-fuentes",
      nombre:      "Dr. William Fuentes Villalba",
      titulo:      "Especialista en Ortodoncia",
      especialidad: "Ortodoncia",
      icono:       "😁",
      descripcion: "Especialista en ortodoncia con amplia experiencia en tratamientos con brackets metálicos, estéticos y alineadores transparentes para niños, jóvenes y adultos.",
      servicios:   ["Brackets metálicos", "Brackets estéticos", "Alineadores transparentes", "Ortopedia maxilar"],
      whatsapp:    "573059370931",
      instagram:   "",
    },
    {
      id:          "andrea-rios",
      nombre:      "Dra. Andrea Carolina Ríos Camargo",
      titulo:      "Especialista en Periodoncia e Implantología",
      especialidad: "Periodoncia e Implantología",
      icono:       "🦷",
      descripcion: "Especialista en periodoncia e implantología con enfoque en la salud de las encías y la rehabilitación con implantes de titanio de alta calidad.",
      servicios:   ["Implantes dentales", "Tratamiento periodontal", "Cirugía de encías", "Regeneración ósea"],
      whatsapp:    "573059370931",
      instagram:   "",
    },
    {
      id:          "estefania-delgado",
      nombre:      "Dra. Estefanía Delgado Rodríguez",
      titulo:      "Especialista en Endodoncia",
      especialidad: "Endodoncia",
      icono:       "🔬",
      descripcion: "Especialista en endodoncia con técnicas modernas para tratamientos de conductos sin dolor. Salva dientes comprometidos con la más alta tasa de éxito.",
      servicios:   ["Tratamiento de conductos", "Retratamiento endodóntico", "Cirugía apical", "Pulpotomía"],
      whatsapp:    "573059370931",
      instagram:   "",
    },
    {
      id:          "diana-garzon",
      nombre:      "Dra. Diana Carolina Garzón",
      titulo:      "Especialista en Estética Dental y Rehabilitación",
      especialidad: "Estética y Rehabilitación Oral",
      icono:       "✨",
      descripcion: "Especialista en estética dental y rehabilitación oral. Diseña sonrisas armoniosas y naturales combinando carillas, coronas y restauraciones de alta estética.",
      servicios:   ["Diseño de sonrisa", "Carillas de porcelana", "Coronas estéticas", "Rehabilitación oral"],
      whatsapp:    "573059370931",
      instagram:   "",
    },
  ],
  servicios: [
    {
      id:          "ortodoncia",
      icono:       "😁",
      nombre:      "Ortodoncia",
      especialista: "Dr. William Fuentes",
      descripcion: "Alineación dental con brackets o alineadores transparentes. Plan personalizado para niños, jóvenes y adultos con seguimiento cercano.",
      features:    ["Brackets y alineadores", "Todas las edades", "Seguimiento cercano"],
    },
    {
      id:          "implantes",
      icono:       "🦷",
      nombre:      "Implantes Dentales",
      especialista: "Dra. Andrea Ríos",
      descripcion: "Implantes de titanio para recuperar tu sonrisa completa. Resultado natural, funcional y permanente con planificación digital.",
      features:    ["Titanio certificado", "Resultado permanente", "Planificación digital"],
    },
    {
      id:          "periodoncia",
      icono:       "🩺",
      nombre:      "Periodoncia",
      especialista: "Dra. Andrea Ríos",
      descripcion: "Diagnóstico y tratamiento de enfermedades de las encías. Prevención y manejo de periodontitis para conservar tus dientes naturales.",
      features:    ["Tratamiento periodontal", "Cirugía de encías", "Mantenimiento"],
    },
    {
      id:          "endodoncia",
      icono:       "🔬",
      nombre:      "Endodoncia",
      especialista: "Dra. Estefanía Delgado",
      descripcion: "Tratamiento de conductos sin dolor para salvar dientes comprometidos. Técnicas modernas y anestesia de última generación.",
      features:    ["Sin dolor", "Alta tasa de éxito", "Técnicas modernas"],
    },
    {
      id:          "estetica",
      icono:       "✨",
      nombre:      "Estética Dental",
      especialista: "Dra. Diana Garzón",
      descripcion: "Diseño de sonrisa, carillas y tratamientos estéticos para transformar tu sonrisa con resultados naturales y armoniosos.",
      features:    ["Diseño de sonrisa", "Carillas porcelana", "Resultado natural"],
    },
    {
      id:          "rehabilitacion",
      icono:       "💎",
      nombre:      "Rehabilitación Oral",
      especialista: "Dra. Diana Garzón",
      descripcion: "Restauración completa de la función y estética dental mediante coronas, puentes y rehabilitaciones integrales personalizadas.",
      features:    ["Coronas y puentes", "Rehabilitación completa", "Alta estética"],
    },
  ],
  testimonios: [
    { nombre: "Valentina M.", servicio: "Ortodoncia",      ciudad: "Bogotá", texto: "El Dr. William Fuentes es excelente. El seguimiento de mi ortodoncia fue muy cercano y el resultado superó mis expectativas.", estrellas: 5 },
    { nombre: "Jorge A.",     servicio: "Implantes",       ciudad: "Bogotá", texto: "La Dra. Andrea Ríos me puso dos implantes y la experiencia fue perfecta. Explica todo con claridad y el resultado es totalmente natural.", estrellas: 5 },
    { nombre: "Camila V.",    servicio: "Endodoncia",      ciudad: "Bogotá", texto: "Tenía mucho miedo de la endodoncia y la Dra. Estefanía me sorprendió — no dolió nada. Muy profesional y tranquilizadora.", estrellas: 5 },
    { nombre: "Daniela R.",   servicio: "Estética Dental", ciudad: "Bogotá", texto: "La Dra. Diana transformó mi sonrisa completamente. Las carillas quedaron perfectas, naturales y armoniosas con mi rostro.", estrellas: 5 },
    { nombre: "Mauricio S.",  servicio: "Periodoncia",     ciudad: "Bogotá", texto: "Tenía periodontitis avanzada y la Dra. Andrea me salvó los dientes. El tratamiento fue muy profesional y los resultados excelentes.", estrellas: 5 },
  ],
  faqs: [
    { pregunta: "¿Son una clínica o profesionales independientes?", respuesta: "Somos profesionales independientes habilitados individualmente ante la Secretaría de Salud, reunidos en un mismo espacio para ofrecer atención especializada integral." },
    { pregunta: "¿Puedo ver a más de un especialista?",             respuesta: "Sí. Al estar en el mismo espacio puedes ser atendido por varios especialistas según tus necesidades, coordinando los tratamientos entre ellos." },
    { pregunta: "¿Qué especialidades cubren?",                      respuesta: "Ortodoncia, periodoncia, implantología, endodoncia, estética dental y rehabilitación oral — cobertura odontológica especializada completa." },
    { pregunta: "¿La endodoncia duele?",                            respuesta: "No. Con anestesia moderna es completamente cómoda. La Dra. Estefanía Delgado utiliza técnicas modernas para una experiencia sin dolor." },
    { pregunta: "¿Cuánto dura un implante dental?",                 respuesta: "Con cuidado adecuado puede durar toda la vida. El proceso completo toma entre 3 y 6 meses con la Dra. Andrea Ríos." },
    { pregunta: "¿La ortodoncia funciona en adultos?",              respuesta: "Sí. El Dr. William Fuentes trabaja con brackets estéticos y alineadores transparentes especialmente populares entre adultos." },
    { pregunta: "¿Cómo agendo mi cita?",                            respuesta: "Por WhatsApp al +57 305 937 0931 o el formulario de esta página. Te orientamos con el especialista adecuado para tu caso." },
    { pregunta: "¿Tienen opciones de financiación?",                respuesta: "Sí, manejamos opciones de pago accesibles. Consulta las alternativas en tu primera cita." },
  ],
  seo: {
    titlePrincipal: "Odontología Especializada Bogotá | Ortodoncia, Implantes, Endodoncia y Estética",
    descripcion:    "Especialistas en ortodoncia, periodoncia, implantología, endodoncia y estética dental en Bogotá. Profesionales independientes certificados. ¡Agenda tu cita!",
    keywords:       "odontología especializada Bogotá, ortodoncia Bogotá, implantes Bogotá, endodoncia Bogotá, estética dental Bogotá",
    canonicalURL:   "https://www.odontologiaespecializada.com.co/",
  },
};

export default CONFIG;
